[workspace]
members = [
  "marigold",
  "marigold-macros",
  "marigold-grammar",
  "marigold-impl",
  "examples/color-palette-picker",
  "examples/csv",
  "examples/multi-consumer",
  "examples/select-all",
  "examples/stateful",
  "examples/bounded-types",
  "tests"
]
resolver = "2"
