[package]
name = "bounded-types"
version = "0.1.0"
edition = "2021"

[dependencies]
marigold = {path = "../../marigold", version = "=0.1.16"}
tokio = {version = "1", features = ["rt", "macros"]}

[dev-dependencies]
tokio = {version = "1", features = ["rt", "macros"]}
trybuild = "1"
